/* File generated with Shader Minifier 1.1.6
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAG_DRAW_H_
# define FRAG_DRAW_H_

const char *draw_frag =
 "#version 120\n"
 "#define iResolution gl_TexCoord[0]\n"
 "#define iTime gl_TexCoord[0].z\n"
 "#define pi (acos(-1.))\n"
 "float t(vec3 v)"
 "{"
   "return v=fract(v*.1031),v+=dot(v,v.yzx+19.19),fract((v.x+v.y)*v.z);"
 "}"
 "vec2 t(vec2 v,float f)"
 "{"
   "float y=cos(f),z=sin(f);"
   "return vec2(v.x*y-v.y*z,v.x*z+v.y*y);"
 "}"
 "float n(vec3 v,vec3 y)"
 "{"
   "return v=abs(v)-y,max(max(v.x,v.y),v.z);"
 "}"
 "vec2 n(const float v)"
 "{"
   "return fract(sin(vec2(v,v+1.))*vec2(43758.5));"
 "}"
 "float v=4.;"
 "float s(vec3 f)"
 "{"
   "float z=1e+09,y=f.y+v+1.;"
   "z=min(z,n(f+vec3(0,v,0),vec3(v,0,0)+1.));"
   "z=min(z,n(f-vec3(v,0,0),vec3(0,v-2.,0)+1.));"
   "float s=f.x+f.z-(v-2.)+fract(iTime)*(v*2.-6.);"
   "z=min(z,max(s-1.,n(f+vec3(v,v,-v+1.),vec3(1.,1.,v))));"
   "z=min(z,max(-s,n(f-vec3(v,v,1.-v),vec3(1.,1.,v))));"
   "f=mod(f+vec3(1,1,1),2.)-1.;"
   "z=max(z,n(f,vec3(.8)));"
   "vec2 i=vec2(1,.2);"
   "z=min(z,y);"
   "return z;"
 "}"
 "vec2 f;"
 "vec3 s(vec3 v,vec3 z)"
 "{"
   "vec3 s=normalize(cross(z,vec3(0.,1.,1.))),y=cross(s,z);"
   "float m=sqrt(f.y),a=m*cos(6.2831*f.x),n=m*sin(6.2831*f.x),x=sqrt(1.-f.y);"
   "vec3 i=vec3(a*s+n*y+x*z);"
   "return normalize(i);"
 "}"
 "vec3 x(vec3 z,vec3 y)"
 "{"
   "vec3 i=vec3(1),n;"
   "for(int m=0;m<4;++m)"
     "{"
       "float x=m==0?5.:0.,a;"
       "for(int r=0;r<100;++r)"
         "{"
           "a=s(z+y*x);"
           "x+=a;"
           "if(abs(a)<.001)"
             "break;"
         "}"
       "if(abs(a)<.001)"
         "{"
           "vec3 r=z+y*x;"
           "vec2 d=vec2(.001,0);"
           "vec3 p=normalize(vec3(s(r+d.xyy)-s(r-d.xyy),s(r+d.yxy)-s(r-d.yxy),s(r+d.yyx)-s(r-d.yyx)));"
           "z=r+p*.02;"
           "y=s(gl_FragCoord.xyz/iResolution.xyz,p);"
           "i/=acos(-1.);"
           "r.xz+=vec2(-1,1);"
           "r.xz+=(f-.5)*max(0.,abs(r.x-r.z)-5.)*.01;"
           "float g=2.;"
           "vec3 c=1.-step(.49,abs(fract(r*g)-.5));"
           "float t=min(c.z,c.x);"
           "g=.125;"
           "g=.25;"
           "r.xz++;"
           "t*=.8-step(0.,(fract(r.x*g)-.5)*(fract(r.z*g)-.5))*.3;"
           "if(r.y<-v-.99)"
             "i*=t;"
         "}"
     "}"
   "vec3 r=normalize(vec3(4,1,-4));"
   "r=vec3(0,1,0);"
   "return i*max(0.,dot(y,r))*3.;"
 "}"
 "void main()"
 "{"
   "vec2 v=gl_FragCoord.xy/iResolution.xy-.5;"
   "float z=iTime+(v.x+iResolution.x*v.y)*1.51269;"
   "f=n(24.4317+iTime+z);"
   "v+=(f-.5)/iResolution.xy;"
   "v.x*=iResolution.x/iResolution.y;"
   "vec3 r=vec3(v*15.,-20.);"
   "r.y-=5./3.;"
   "r.x+=.75;"
   "vec3 y=vec3(0,0,1);"
   "r.yz=t(r.yz,atan(1.,sqrt(2.)));"
   "y.yz=t(y.yz,atan(1.,sqrt(2.)));"
   "r.xz=t(r.xz,pi/4.);"
   "y.xz=t(y.xz,pi/4.);"
   "vec4 m=vec4(x(r,y)*(1.-dot(v,v)*.5),1);"
   "gl_FragColor=m;"
 "}";

#endif // FRAG_DRAW_H_
